# Generated by Django 3.2.6 on 2021-09-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Loan_ID', models.CharField(max_length=255)),
                ('Gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=6)),
                ('Married', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=3)),
                ('Dependents', models.IntegerField()),
                ('Education', models.CharField(choices=[('Graduate', 'graduate'), ('Not', 'not')], max_length=8)),
                ('Self_employed', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=3)),
                ('ApplicantIncome', models.BigIntegerField()),
                ('CoapplicantIncome', models.BigIntegerField()),
                ('LoanAmount', models.BigIntegerField()),
                ('Loan_Amount_Term', models.BigIntegerField()),
                ('Credit_History', models.FloatField()),
                ('Property_Area', models.CharField(choices=[('Urban', 'urban'), ('Rural', 'rural')], max_length=5)),
                ('Loan_Status', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=3)),
            ],
        ),
    ]
