# Generated by Django 3.2.6 on 2021-09-02 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_observation_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='Property_Area',
        ),
    ]
